"""Anonymous SDK feeds and validated public Gamma/CLOB entry snapshots.

HTTP discovery deliberately reads wire dictionaries: SDK Gamma normalization drops
``eventStartTime``. Current CLOB flags/fees are never taken from a signing cache.
Only ``AsyncPublicClient`` is constructed. No account or order API is used.

Raw spot history is bounded by the configured long window plus 60 seconds and a
hard point count. Missing source seconds remain missing. Snapshot callers drive
metadata retries (30 seconds per round, at most two reads per call), retaining at
most 12 rounds for one hour after expiry. Delayed labels beyond this horizon are
reported missing, not inferred. The synchronous observer must persist promptly;
a failure prevents entry snapshots while the independent held-token book remains
available. Call snapshot regularly even when it raises DataUnavailable.
"""

from __future__ import annotations

import asyncio
import json
import re
import time
from collections.abc import Callable, Iterable
from dataclasses import dataclass, replace
from datetime import UTC, datetime
from decimal import Decimal, InvalidOperation
from types import TracebackType
from typing import Any, Literal, Self

import httpx
from polymarket import AsyncPublicClient
from polymarket.models.clob.order_book import OrderBook
from polymarket.models.rtds_events import (
    CryptoPricesChainlinkEvent,
    CryptoPricesChainlinkTwapEvent,
)
from polymarket.streams import CryptoPricesChainlinkTwapSpec, CryptoPricesSpec

from btc5m.config import Config
from btc5m.domain import Book, Level, Market, PricePoint, Snapshot
from btc5m.streams import PublicStreams

SOURCE = "https://data.chain.link/streams/btc-usd-twap-60s-streams"
GAMMA = "https://gamma-api.polymarket.com"
CLOB = "https://clob.polymarket.com"
RULE = (
    'This market will resolve to "Up" if the time-weighted average price (TWAP) '
    "of Bitcoin, generated by Chainlink, of the time range specified in the title "
    "is greater than or equal to the price at the beginning of that range. "
    'Otherwise, it will resolve to "Down". '
    "The resolution source for this market is information from Chainlink, "
    "specifically the BTC/USD TWAP data stream available at " + SOURCE + ". "
    "Please note that this market is about the price according to the TWAP "
    "Chainlink data stream for the asset pair BTC/USD, not according to any "
    "other sources or spot markets."
)
ROUND_RE = re.compile(r"btc-updown-5m-([0-9]{10})\Z")
CONDITION_RE = re.compile(r"0x[0-9a-fA-F]{64}\Z")
TICKS = frozenset(map(Decimal, (".1", ".01", ".005", ".001", ".0025", ".0001")))
HTTP_TIMEOUT = 5.0
ANCHOR_TOLERANCE = Decimal("0.00000001")


class DataUnavailable(Exception):
    """An explicit non-actionable input outcome; code is safe to persist."""

    def __init__(self, code: str) -> None:
        self.code = code
        super().__init__(code)


@dataclass
class _Round:
    slug: str
    start_s: int
    condition_id: str
    official: Decimal | None = None
    captured: Decimal | None = None
    conflict: bool = False
    final: Decimal | None = None
    final_conflict: bool = False
    next_poll: float = 0.0
    provenance: str = ""
    received_ms: int = 0


@dataclass(frozen=True)
class _BookRead:
    book: Book
    condition_id: str
    tick: Decimal
    minimum: Decimal


def _decimal(value: object, *, positive: bool = True) -> Decimal:
    if isinstance(value, bool) or not isinstance(value, str | int | float | Decimal):
        raise DataUnavailable("INVALID_NUMBER")
    try:
        result = Decimal(str(value))
    except InvalidOperation as exc:
        raise DataUnavailable("INVALID_NUMBER") from exc
    if not result.is_finite() or result < 0 or (positive and result == 0):
        raise DataUnavailable("INVALID_NUMBER")
    return result


def _mapping(value: object) -> dict[str, Any]:
    if not isinstance(value, dict):
        raise DataUnavailable("INVALID_METADATA")
    return value


def _array(value: object) -> list[Any]:
    if isinstance(value, str):
        try:
            value = json.loads(value)
        except ValueError as exc:
            raise DataUnavailable("INVALID_METADATA") from exc
    if not isinstance(value, list):
        raise DataUnavailable("INVALID_METADATA")
    return value


def _timestamp(value: object) -> int:
    # Explicit ms units. Never guess seconds/microseconds into valid entry data.
    if type(value) is not int or not 1_000_000_000_000 <= value < 100_000_000_000_000:
        raise DataUnavailable("INVALID_TIMESTAMP")
    return value


def _iso_ms(value: object) -> int:
    if not isinstance(value, str):
        raise DataUnavailable("INVALID_MARKET_TIME")
    try:
        stamp = datetime.fromisoformat(value.replace("Z", "+00:00"))
    except ValueError as exc:
        raise DataUnavailable("INVALID_MARKET_TIME") from exc
    if stamp.tzinfo is None:
        raise DataUnavailable("INVALID_MARKET_TIME")
    return int(stamp.timestamp() * 1000)


def _token(value: object) -> str:
    if not isinstance(value, str) or len(value) > 78 or not value.isascii() or not value.isdigit():
        raise DataUnavailable("INVALID_TOKEN")
    if not 0 < int(value) < 2**256:
        raise DataUnavailable("INVALID_TOKEN")
    return value


def _condition(value: object) -> str:
    if not isinstance(value, str) or CONDITION_RE.fullmatch(value) is None:
        raise DataUnavailable("INVALID_CONDITION")
    return value


def _flag(raw: dict[str, Any], key: str, required: bool) -> None:
    if raw.get(key) is not required:
        raise DataUnavailable("UNSUPPORTED_MARKET_STATE")


def _token_map(labels: list[Any], ids: list[Any]) -> dict[str, str]:
    if len(labels) != 2 or set(labels) != {"Up", "Down"} or len(ids) != 2:
        raise DataUnavailable("AMBIGUOUS_TOKENS")
    result = {str(label): _token(token) for label, token in zip(labels, ids, strict=True)}
    if result["Up"] == result["Down"]:
        raise DataUnavailable("AMBIGUOUS_TOKENS")
    return result


class MarketData:
    """Own anonymous transports; injected client/HTTP/seconds clocks aid replay."""

    def __init__(
        self,
        config: Config,
        *,
        client: Any = None,
        http_client: httpx.AsyncClient | None = None,
        clock: Callable[[], float] = time.time,
        monotonic: Callable[[], float] = time.monotonic,
        observer: Callable[[dict[str, object]], None] | None = None,
        enhanced: bool = False,
    ) -> None:
        self.config = config
        self._client = client if client is not None else AsyncPublicClient()
        self._http = (
            http_client if http_client is not None else httpx.AsyncClient(timeout=HTTP_TIMEOUT)
        )
        self._clock, self._mono, self._observer = clock, monotonic, observer
        self._points: dict[str, dict[int, PricePoint]] = {"spot": {}, "twap60": {}}
        self._receipts: dict[str, float] = {}
        self._stream_error: dict[str, str] = {}
        self._conflicting_points: dict[str, set[int]] = {"spot": set(), "twap60": set()}
        self._rounds: dict[str, _Round] = {}
        self._retained_rounds: set[str] = set()
        self._tasks: list[asyncio.Task[None]] = []
        self._closed = False
        self._observer_failed = False
        self._snapshot_lock = asyncio.Lock()
        self._history_ms = (config.strategy.volatility_long_seconds + 60) * 1000
        self._max_points = (config.strategy.volatility_long_seconds + 60) * 2 + 100
        self.streams = (
            PublicStreams(config, clock=clock, observer=self._stream_observation)
            if enhanced
            else None
        )
        self._cached_snapshot: Snapshot | None = None
        self._cached_at = float("-inf")
        self._logged_stream_books: dict[str, Book] = {}

    def _stream_observation(self, record: dict[str, object]) -> None:
        if record.get("kind") == "stream_unavailable" and record.get("stream") == "books":
            self._cached_at = float("-inf")
        self._emit(str(record["kind"]), **{k: v for k, v in record.items() if k != "kind"})

    def current_snapshot(self) -> Snapshot | None:
        """Fresh model input independent of whether a new entry is currently eligible."""
        cached, now = self._cached_snapshot, self._now()
        if cached is None or self._mono() - self._cached_at > HTTP_TIMEOUT or self._observer_failed:
            return None
        if now // 300000 != cached.market.start_s // 300:
            return None
        state = self._rounds.get(cached.market.slug)
        if state is None or state.conflict:
            return None
        try:
            spot, twap = self._latest("spot", now), self._latest("twap60", now)
            books = []
            for prior in (cached.up_book, cached.down_book):
                if self.streams and prior.token_id in self.streams.pending_books:
                    return None
                current = self.streams.books.get(prior.token_id, prior) if self.streams else prior
                self._fresh(
                    current.timestamp_ms, current.received_ms, now, self.config.data.max_book_age_ms
                )
                if any(
                    level.price % cached.market.tick_size
                    for level in (*current.bids, *current.asks)
                ):
                    return None
                books.append(current)
                if self.streams and self._logged_stream_books.get(current.token_id) != current:
                    self._emit(
                        "book",
                        source="polymarket:market-websocket",
                        token_id=current.token_id,
                        condition_id=cached.market.condition_id,
                        source_ms=current.timestamp_ms,
                        tick_size=str(cached.market.tick_size),
                        min_order_size=str(cached.market.min_order_size),
                        bids=[{"price": str(x.price), "size": str(x.size)} for x in current.bids],
                        asks=[{"price": str(x.price), "size": str(x.size)} for x in current.asks],
                    )
                    self._logged_stream_books[current.token_id] = current
            return replace(
                cached,
                now_ms=now,
                spot=spot,
                twap60=twap,
                up_book=books[0],
                down_book=books[1],
                history=tuple(self._points["spot"][k] for k in sorted(self._points["spot"])),
                exchange_history=self.streams.exchange_history if self.streams else (),
            )
        except DataUnavailable:
            return None

    def final_reference(self, market: Market) -> tuple[Decimal, Decimal] | None:
        """Official public labels for simulated settlement, never chain finality."""
        state = self._rounds.get(market.slug)
        if (
            state is None
            or state.condition_id != market.condition_id
            or state.conflict
            or state.final_conflict
            or state.official is None
            or state.final is None
            or self._now() < market.end_s * 1000
            or market.reference_price is None
            or abs(state.official - market.reference_price) > ANCHOR_TOLERANCE
        ):
            return None
        return state.official, state.final

    def retain_markets(self, markets: tuple[Market, ...]) -> None:
        """Resume official label polling for simulated holdings after restart.

        Stored references are comparison anchors; fresh public metadata still has
        to verify the rule, identity and final label before simulated settlement.
        """
        if len({m.slug for m in markets}) > 6:
            raise DataUnavailable("TOO_MANY_RETAINED_MARKETS")
        self._retained_rounds = {m.slug for m in markets}
        for market in markets:
            if market.slug not in self._rounds:
                self._rounds[market.slug] = _Round(
                    market.slug,
                    market.start_s,
                    market.condition_id,
                    captured=market.reference_price,
                    next_poll=0,
                )
            elif self._rounds[market.slug].condition_id != market.condition_id:
                raise DataUnavailable("METADATA_IDENTITY_MISMATCH")

    def restore_history(self, records: Iterable[dict[str, Any]]) -> int:
        """Restore this paper journal's recent source points without renewing freshness.

        Real feed receipt is still required for both streams after startup. Source
        timestamps, missing seconds and conflicting points retain their meaning.
        """
        if self._tasks or any(self._points.values()):
            raise DataUnavailable("HISTORY_RESTORE_REQUIRES_NEW_ADAPTER")
        now = self._now()
        restored = 0
        for row in records:
            kind = row.get("kind")
            if kind == "price_conflict":
                stream = row.get("stream")
                if stream in self._conflicting_points:
                    self._conflicting_points[stream].add(_timestamp(row.get("source_ms")))
                continue
            if kind not in ("spot", "twap60"):
                continue
            if row.get("source") != (SOURCE if kind == "twap60" else "prices.crypto.chainlink"):
                raise DataUnavailable("HISTORY_SOURCE_MISMATCH")
            stamp, received = _timestamp(row.get("source_ms")), _timestamp(row.get("received_ms"))
            if max(stamp, received) > now or min(stamp, received) < now - self._history_ms:
                continue
            point = PricePoint(kind, stamp, received, _decimal(row.get("price")))
            prior = self._points[kind].get(stamp)
            if prior is not None and prior.price != point.price:
                self._conflicting_points[kind].add(stamp)
            elif prior is None:
                self._points[kind][stamp] = point
                restored += 1
        for kind, points in self._points.items():
            for old in sorted(points)[: -self._max_points]:
                del points[old]
            self._conflicting_points[kind].intersection_update(points)
        return restored

    def _now(self) -> int:
        return int(self._clock() * 1000)

    def _emit(self, kind: str, **fields: object) -> None:
        if self._observer is None or self._observer_failed:
            return
        now = self._now()
        record: dict[str, object] = {
            "kind": kind,
            "received_ms": now,
            "received_utc": datetime.fromtimestamp(now / 1000, UTC).isoformat(),
            **fields,
        }
        try:
            self._observer(json.loads(json.dumps(record, default=str)))
        except Exception:
            self._observer_failed = True

    async def __aenter__(self) -> Self:
        if self._closed or self._tasks:
            raise DataUnavailable("INVALID_LIFECYCLE")
        self._tasks = [
            asyncio.create_task(self._consume("spot")),
            asyncio.create_task(self._consume("twap60")),
        ]
        if self.streams:
            await self.streams.start()
        return self

    async def __aexit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        traceback: TracebackType | None,
    ) -> None:
        await self.close()

    async def close(self) -> None:
        if self._closed:
            return
        self._closed = True
        if self.streams:
            await self.streams.close()
        for task in self._tasks:
            task.cancel()
        results = await asyncio.gather(
            self._client.close(), self._http.aclose(), *self._tasks, return_exceptions=True
        )
        for result in results[:2]:
            if isinstance(result, BaseException):
                raise result

    async def _consume(self, kind: Literal["spot", "twap60"]) -> None:
        spec = (
            CryptoPricesSpec(topic="prices.crypto.chainlink", symbols=("btc/usd",))
            if kind == "spot"
            else CryptoPricesChainlinkTwapSpec(window_seconds=60, symbols=("btc/usd",))
        )
        while not self._closed:
            handle = None
            try:
                async with asyncio.timeout(HTTP_TIMEOUT):
                    handle = await self._client.subscribe(spec)
                while not self._closed:
                    # asyncio's timeout uses the event loop's monotonic clock.
                    async with asyncio.timeout(self.config.data.max_price_age_ms / 1000):
                        event = await anext(handle)
                    self._ingest(kind, event)
            except asyncio.CancelledError:
                raise
            except Exception as exc:
                code = exc.code if isinstance(exc, DataUnavailable) else "STREAM_DISCONNECTED"
                self._stream_error[kind] = code
                self._receipts.pop(kind, None)
                self._emit(
                    "stream_unavailable", stream=kind, code=code, error_type=type(exc).__name__
                )
            finally:
                if handle is not None:
                    try:
                        async with asyncio.timeout(HTTP_TIMEOUT):
                            await handle.close()
                    except Exception as exc:
                        self._emit(
                            "stream_close_failed", stream=kind, error_type=type(exc).__name__
                        )
            if not self._closed:
                await asyncio.sleep(1)

    def _ingest(self, kind: Literal["spot", "twap60"], event: object) -> None:
        if kind == "spot":
            if not isinstance(event, CryptoPricesChainlinkEvent):
                raise DataUnavailable("UNKNOWN_STREAM_KIND")
        elif (
            not isinstance(event, CryptoPricesChainlinkTwapEvent)
            or event.payload.window_seconds != 60
        ):
            raise DataUnavailable("UNKNOWN_STREAM_KIND")
        assert isinstance(event, CryptoPricesChainlinkEvent | CryptoPricesChainlinkTwapEvent)
        if event.payload.symbol != "btc/usd" or event.type != "update":
            raise DataUnavailable("UNKNOWN_STREAM_KIND")
        stamp = _timestamp(event.payload.timestamp)
        now = self._now()
        if stamp > now + self.config.data.future_tolerance_ms:
            raise DataUnavailable("FUTURE_PRICE")
        point = PricePoint(kind, stamp, now, _decimal(event.payload.value))
        points = self._points[kind]
        previous = points.get(stamp)
        if previous is not None:
            if previous.price != point.price:
                self._conflicting_points[kind].add(stamp)
                self._emit("price_conflict", stream=kind, source_ms=stamp)
                if kind == "twap60" and stamp % 300000 == 0:
                    state = self._rounds.get(f"btc-updown-5m-{stamp // 1000}")
                    if state is not None:
                        state.conflict = True
            return
        newest = max(points, default=0)
        if stamp < newest - self._history_ms:
            return
        points[stamp] = point
        if stamp > newest:
            self._receipts[kind] = self._mono()
            self._stream_error.pop(kind, None)
        cutoff = max(stamp, newest) - self._history_ms
        for old in sorted(points):
            if old < cutoff or len(points) > self._max_points:
                del points[old]
        self._conflicting_points[kind].intersection_update(points)
        self._emit(
            kind,
            source_ms=stamp,
            price=str(point.price),
            source=SOURCE if kind == "twap60" else "prices.crypto.chainlink",
        )
        if kind == "twap60" and stamp % 300000 == 0:
            state = self._rounds.get(f"btc-updown-5m-{stamp // 1000}")
            if state is not None:
                state.captured = point.price
                self._compare(state)
                self._emit_anchor(state)

    def _fresh(self, stamp: int, received: int, now: int, age: int) -> None:
        if any(t > now + self.config.data.future_tolerance_ms for t in (stamp, received)):
            raise DataUnavailable("FUTURE_DATA")
        if now - stamp > age or now - received > age:
            raise DataUnavailable("STALE_DATA")

    def _latest(self, kind: str, now: int) -> PricePoint:
        points = self._points[kind]
        if not points:
            raise DataUnavailable(self._stream_error.get(kind, "STREAM_WARMUP"))
        if (
            kind not in self._receipts
            or self._mono() - self._receipts[kind] > self.config.data.max_price_age_ms / 1000
        ):
            raise DataUnavailable("STREAM_SILENT")
        point = points[max(points)]
        self._fresh(point.timestamp_ms, point.received_ms, now, self.config.data.max_price_age_ms)
        if self._conflicting_points[kind]:
            raise DataUnavailable("PRICE_CONFLICT")
        return point

    async def _raw(self, url: str, **kwargs: Any) -> dict[str, Any]:
        try:
            async with asyncio.timeout(HTTP_TIMEOUT):
                response = await self._http.get(url, timeout=HTTP_TIMEOUT, **kwargs)
                response.raise_for_status()
                return _mapping(json.loads(response.text, parse_float=Decimal))
        except DataUnavailable:
            raise
        except Exception as exc:
            self._emit("http_unavailable", endpoint=url, error_type=type(exc).__name__)
            raise DataUnavailable("HTTP_UNAVAILABLE") from exc

    async def _read_book(self, token_id: str) -> _BookRead:
        _token(token_id)
        if self._closed:
            raise DataUnavailable("CLOSED")
        try:
            async with asyncio.timeout(HTTP_TIMEOUT):
                raw: OrderBook = await self._client.get_order_book(token_id=token_id)
            now = self._now()
            if str(raw.asset_id) != token_id or raw.neg_risk is not False or raw.timestamp is None:
                raise DataUnavailable("INVALID_BOOK_METADATA")
            stamp = _timestamp(int(raw.timestamp.timestamp() * 1000))
            tick, minimum = _decimal(raw.tick_size), _decimal(raw.min_order_size)
            if tick not in TICKS:
                raise DataUnavailable("UNSUPPORTED_TICK")
            result = Book(
                token_id,
                stamp,
                now,
                tuple(Level(level.price, level.size) for level in raw.bids),
                tuple(Level(level.price, level.size) for level in raw.asks),
            )
            self._fresh(stamp, now, now, self.config.data.max_book_age_ms)
            if result.bids and result.asks and result.bids[0].price >= result.asks[0].price:
                raise DataUnavailable("CROSSED_BOOK")
            self._emit(
                "book",
                token_id=token_id,
                source_ms=stamp,
                condition_id=str(raw.condition_id),
                tick_size=str(tick),
                min_order_size=str(minimum),
                bids=[{"price": str(x.price), "size": str(x.size)} for x in result.bids],
                asks=[{"price": str(x.price), "size": str(x.size)} for x in result.asks],
            )
            return _BookRead(result, _condition(str(raw.condition_id)), tick, minimum)
        except DataUnavailable:
            raise
        except Exception as exc:
            self._emit("book_unavailable", token_id=token_id, error_type=type(exc).__name__)
            raise DataUnavailable("BOOK_UNAVAILABLE") from exc

    async def book(self, token_id: str) -> Book:
        """Read a held asset even with no usable current market or reference feeds."""
        if self.streams and token_id in self.streams.books:
            book = self.streams.books[token_id]
            try:
                self._fresh(
                    book.timestamp_ms,
                    book.received_ms,
                    self._now(),
                    self.config.data.max_book_age_ms,
                )
                return book
            except DataUnavailable:
                self._emit("book_transport", token_id=token_id, code="REST_RECOVERY")
        return (await self._read_book(token_id)).book

    def _compare(self, state: _Round) -> None:
        if state.official is not None and state.captured is not None:
            if abs(state.official - state.captured) > ANCHOR_TOLERANCE:
                state.conflict = True

    def _reference(
        self, state: _Round
    ) -> tuple[Decimal | None, Literal["official", "boundary", "missing", "conflict"]]:
        value = state.official
        if value is None and self.config.data.allow_captured_anchor:
            value = state.captured
        if state.conflict:
            return value, "conflict"
        return (
            value,
            "official"
            if state.official is not None
            else "boundary"
            if value is not None
            else "missing",
        )

    def _emit_anchor(self, state: _Round) -> None:
        value, status = self._reference(state)
        self._emit(
            "anchor",
            slug=state.slug,
            source_ms=state.start_s * 1000,
            price=str(value) if value is not None else None,
            status=status,
            captured_price=str(state.captured) if state.captured is not None else None,
            official_price=str(state.official) if state.official is not None else None,
            provenance=state.provenance,
        )

    def _metadata(self, state: _Round, metadata: object, provenance: str) -> None:
        raw = {} if metadata is None else _mapping(metadata)
        state.provenance, state.received_ms = provenance, self._now()
        opening = raw.get("priceToBeat")
        if opening is not None:
            price = _decimal(opening)
            if state.official is not None and abs(state.official - price) > ANCHOR_TOLERANCE:
                state.conflict = True
            elif state.official is None:
                state.official = price
        self._compare(state)
        self._emit_anchor(state)
        final = raw.get("finalPrice")
        if final is not None:
            price = _decimal(final)
            if self._now() < (state.start_s + 300) * 1000:
                raise DataUnavailable("PREMATURE_FINAL_REFERENCE")
            if state.final is not None and abs(state.final - price) > ANCHOR_TOLERANCE:
                state.final_conflict = True
            changed = state.final is None or state.final_conflict
            if state.final is None:
                state.final = price
            if changed:
                self._emit(
                    "final_reference",
                    slug=state.slug,
                    source_ms=(state.start_s + 300) * 1000,
                    price=str(state.final),
                    status="conflict" if state.final_conflict else "official",
                    provenance=provenance,
                )

    def _retire_rounds(self) -> None:
        now = self._now()
        for slug, state in list(self._rounds.items()):
            if slug in self._retained_rounds:
                continue
            if now > (state.start_s + 300 + 3600) * 1000 or len(self._rounds) > 12 + len(
                self._retained_rounds
            ):
                self._emit(
                    "reference_retired",
                    slug=slug,
                    opening_status=self._reference(state)[1],
                    final_status="missing"
                    if state.final is None
                    else "conflict"
                    if state.final_conflict
                    else "official",
                )
                del self._rounds[slug]

    async def _poll_due(self) -> None:
        self._retire_rounds()
        mono = self._mono()
        due = sorted(
            (s for s in self._rounds.values() if s.next_poll <= mono), key=lambda s: s.next_poll
        )[:2]
        for state in due:
            state.next_poll = mono + 30
            provenance = f"{GAMMA}/events/slug/{state.slug}?include_chat=false; SDK get_event"
            try:
                async with asyncio.timeout(HTTP_TIMEOUT):
                    event = await self._client.get_event(slug=state.slug, include_chat=False)
                if (
                    event.slug != state.slug
                    or len(event.markets) != 1
                    or str(event.markets[0].condition_id) != state.condition_id
                ):
                    raise DataUnavailable("METADATA_IDENTITY_MISMATCH")
                for candidate in (event, event.markets[0]):
                    if (
                        candidate.resolution.source != SOURCE
                        or " ".join((candidate.description or "").split()) != RULE
                    ):
                        # This is incompatible official evidence for an already
                        # matched contract, not a retryable transport failure.
                        state.conflict = True
                        raise DataUnavailable("UNSUPPORTED_RULE")
                if (
                    event.schedule.start_time is None
                    or event.schedule.end_date is None
                    or int(event.schedule.start_time.timestamp()) != state.start_s
                    or int(event.schedule.end_date.timestamp()) != state.start_s + 300
                ):
                    raise DataUnavailable("METADATA_IDENTITY_MISMATCH")
                self._metadata(state, event.metadata, provenance)
            except Exception as exc:
                self._emit(
                    "metadata_unavailable",
                    slug=state.slug,
                    code=exc.code if isinstance(exc, DataUnavailable) else "HTTP_UNAVAILABLE",
                    error_type=type(exc).__name__,
                    provenance=provenance,
                )

    async def snapshot(self, now_ms: int | None = None) -> Snapshot:
        if self._closed:
            raise DataUnavailable("CLOSED")
        async with self._snapshot_lock:
            try:
                await self._poll_due()
                if self.streams:
                    cached = self.current_snapshot() if self._mono() - self._cached_at < 2 else None
                    if cached is not None:
                        return cached
                now = self._now() if now_ms is None else _timestamp(now_ms)
                start = now // 300000 * 300
                slug = f"btc-updown-5m-{start}"
                provenance = f"{GAMMA}/events/slug/{slug}?include_chat=false"
                event = await self._raw(
                    f"{GAMMA}/events/slug/{slug}", params={"include_chat": "false"}
                )
                self._emit(
                    "discovery",
                    slug=slug,
                    source_ms=start * 1000,
                    stage="received",
                    provenance=provenance,
                    raw_event=event,
                )
                raw = self._parse_event(event, slug, start)
                condition = _condition(raw.get("conditionId"))
                tokens = _token_map(_array(raw.get("outcomes")), _array(raw.get("clobTokenIds")))
                if slug not in self._rounds:
                    point = self._points["twap60"].get(start * 1000)
                    self._rounds[slug] = _Round(
                        slug,
                        start,
                        condition,
                        captured=point.price if point is not None else None,
                        next_poll=self._mono() + 30,
                    )
                self._retire_rounds()
                state = self._rounds[slug]
                if state.condition_id != condition:
                    state.conflict = True
                    raise DataUnavailable("MARKET_IDENTITY_CHANGED")
                if start * 1000 in self._conflicting_points["twap60"]:
                    state.conflict = True
                self._metadata(state, event.get("eventMetadata"), provenance)
                flags, fees, up, down = await asyncio.gather(
                    self._raw(f"{CLOB}/markets/{condition}"),
                    self._raw(f"{CLOB}/clob-markets/{condition}"),
                    self._read_book(tokens["Up"]),
                    self._read_book(tokens["Down"]),
                )
                tick, minimum, rate, exponent = self._trading_metadata(
                    flags, fees, slug, condition, tokens
                )
                for book in (up, down):
                    mismatches = [
                        (name, expected, actual)
                        for name, expected, actual in (
                            ("condition_id", condition, book.condition_id),
                            ("tick_size", tick, book.tick),
                            ("min_order_size", minimum, book.minimum),
                        )
                        if expected != actual
                    ]
                    for name, expected, actual in mismatches:
                        self._emit(
                            "metadata_rejected",
                            code="TRADING_METADATA_CHANGED",
                            slug=slug,
                            condition_id=condition,
                            token_id=book.book.token_id,
                            endpoint=f"{CLOB}/book",
                            compared_field=name,
                            expected=str(expected),
                            actual=str(actual),
                        )
                    if mismatches:
                        raise DataUnavailable("TRADING_METADATA_CHANGED")
                # now_ms chooses the initial round; final validation always uses
                # the advancing injected UTC clock after all network work.
                final_now = self._now()
                if final_now // 300000 != start // 300:
                    raise DataUnavailable("ROUND_CHANGED")
                for book in (up.book, down.book):
                    self._fresh(
                        book.timestamp_ms,
                        book.received_ms,
                        final_now,
                        self.config.data.max_book_age_ms,
                    )
                value, status = self._reference(state)
                market = Market(
                    slug,
                    condition,
                    start,
                    start + 300,
                    tokens["Up"],
                    tokens["Down"],
                    value,
                    "eventMetadata.priceToBeat"
                    if state.official is not None
                    else "chainlink_twap60_exact_boundary"
                    if value is not None
                    else None,
                    SOURCE,
                    tick,
                    minimum,
                    rate,
                    exponent,
                    True,
                    True,
                    status,
                    start * 1000 if value is not None else None,
                    state.received_ms,
                    state.provenance,
                )
                self._emit(
                    "discovery",
                    slug=slug,
                    source_ms=start * 1000,
                    provenance=provenance,
                    stage="validated",
                    raw_clob_market=flags,
                    raw_clob_fees=fees,
                    reference_status=status,
                )
                spot, twap = self._latest("spot", final_now), self._latest("twap60", final_now)
                if self._observer_failed:
                    raise DataUnavailable("OBSERVER_FAILED")
                if self.streams:
                    await self.streams.select_market(
                        (market.up_token, market.down_token), market.condition_id
                    )
                result = Snapshot(
                    market,
                    up.book,
                    down.book,
                    spot,
                    twap,
                    tuple(self._points["spot"][key] for key in sorted(self._points["spot"])),
                    final_now,
                    self.streams.exchange_history if self.streams else (),
                )
                self._cached_snapshot, self._cached_at = result, self._mono()
                return result
            except DataUnavailable as exc:
                self._emit("snapshot_unavailable", code=exc.code)
                raise
            except (ValueError, TypeError, KeyError, AttributeError) as exc:
                self._emit(
                    "snapshot_unavailable", code="INVALID_METADATA", error_type=type(exc).__name__
                )
                raise DataUnavailable("INVALID_METADATA") from exc

    def _parse_event(self, event: dict[str, Any], slug: str, start: int) -> dict[str, Any]:
        markets = _array(event.get("markets"))
        if event.get("slug") != slug or len(markets) != 1:
            raise DataUnavailable("WRONG_MARKET")
        market = _mapping(markets[0])
        if market.get("slug") != slug or ROUND_RE.fullmatch(slug) is None:
            raise DataUnavailable("WRONG_MARKET")
        if (
            _iso_ms(market.get("eventStartTime")) != start * 1000
            or _iso_ms(market.get("endDate")) != (start + 300) * 1000
        ):
            raise DataUnavailable("WRONG_ROUND_TIME")
        if (
            _iso_ms(event.get("startTime")) != start * 1000
            or _iso_ms(event.get("endDate")) != (start + 300) * 1000
        ):
            raise DataUnavailable("WRONG_ROUND_TIME")
        for raw in (market, event):
            if (
                raw.get("resolutionSource") != SOURCE
                or " ".join(str(raw.get("description", "")).split()) != RULE
            ):
                raise DataUnavailable("UNSUPPORTED_RULE")
        if market.get("negRisk") is not False:
            raise DataUnavailable("UNSUPPORTED_MARKET_STATE")
        return market

    def _trading_metadata(
        self,
        flags: dict[str, Any],
        fees: dict[str, Any],
        slug: str,
        condition: str,
        tokens: dict[str, str],
    ) -> tuple[Decimal, Decimal, Decimal, int]:
        for name, wanted in (
            ("active", True),
            ("accepting_orders", True),
            ("enable_order_book", True),
            ("closed", False),
            ("archived", False),
            ("neg_risk", False),
        ):
            _flag(flags, name, wanted)
        if (
            flags.get("condition_id") != condition
            or flags.get("market_slug") != slug
            or fees.get("c") != condition
            or fees.get("v") != "v1"
        ):
            raise DataUnavailable("UNSUPPORTED_MARKET_SCHEMA")
        _flag(fees, "ao", True)
        for rows, label_key, token_key in (
            (_array(flags.get("tokens")), "outcome", "token_id"),
            (_array(fees.get("t")), "o", "t"),
        ):
            mapping = _token_map(
                [_mapping(row).get(label_key) for row in rows],
                [_mapping(row).get(token_key) for row in rows],
            )
            if mapping != tokens:
                raise DataUnavailable("TOKEN_MAPPING_CHANGED")
        fee = _mapping(fees.get("fd"))
        if set(fee) != {"r", "e", "to"} or fee.get("to") is not True:
            raise DataUnavailable("UNSUPPORTED_FEE_SCHEMA")
        rate, exponent = _decimal(fee["r"], positive=False), _decimal(fee["e"])
        if rate > 1 or exponent != exponent.to_integral_value() or exponent > 10:
            raise DataUnavailable("UNSUPPORTED_FEE_SCHEMA")
        tick, minimum = _decimal(fees.get("mts")), _decimal(fees.get("mos"))
        if tick not in TICKS:
            self._emit(
                "metadata_rejected",
                code="TRADING_METADATA_CHANGED",
                slug=slug,
                condition_id=condition,
                endpoint=f"{CLOB}/clob-markets/{condition}",
                compared_field="tick_size",
                expected="supported_tick_set",
                actual=str(tick),
                supported_ticks=sorted(str(value) for value in TICKS),
            )
            raise DataUnavailable("TRADING_METADATA_CHANGED")
        for name, expected, wire_value in (
            ("tick_size", tick, flags.get("minimum_tick_size")),
            ("min_order_size", minimum, flags.get("minimum_order_size")),
        ):
            actual = _decimal(wire_value)
            if expected != actual:
                self._emit(
                    "metadata_rejected",
                    code="TRADING_METADATA_CHANGED",
                    slug=slug,
                    condition_id=condition,
                    endpoint=f"{CLOB}/markets/{condition}",
                    compared_field=name,
                    expected=str(expected),
                    actual=str(actual),
                )
                raise DataUnavailable("TRADING_METADATA_CHANGED")
        return tick, minimum, rate, int(exponent)
